### ISSUE TITLE
Possibly unnecessary use of `scale()`

### ISSUE THREAD

**Issue by xiangzhu** [stephenslab/LDshrink#2]
@CreRecombinase spotted the following line that might be not necessary.

https://github.com/stephenslab/LDshrink/blob/a8fdff30a4df3b202a9932aeb9aa4d3debc7d535/R/LDshrink.R#L8

**Comment by CreRecombinase** [comment]
This is fixed as of version `df6147e4ebe0a6136a3eb21b90baa6cb5bc13a2e`
