### ISSUE TITLE
Name the package

### ISSUE THREAD

**Issue by xiangzhu** [stephenslab/ldshrink#20]
This thread is based on http://r-pkgs.had.co.nz/package.html#naming.

- [x] Pick a unique name you can easily Google. Done: top 1 search in my side.
<img width="785" alt="screen shot 2018-10-04 at 4 23 42 pm" src="https://user-images.githubusercontent.com/5986023/46508358-100b7700-c7f2-11e8-9c89-3d1fd89f13e2.png">

- [ ] Avoid using both upper and lower case letters. To do: `LDshrink -> ldshrink`. This seems to be a global change.

**Comment by pcarbo** [comment]
@xiangzhu I think `LDshrink` is justified because "LD" is a very commonly used acronym in genetics, but if you prefer `ldshrink`, I'm okay with that, too.

**Comment by xiangzhu** [comment]
Thanks Peter! I am simply following Wichham's package book, starting from the package name ... :)

On a relate note, LD score regression was named as `ldsc`: https://github.com/bulik/ldsc

**Comment by pcarbo** [comment]
@xiangzhou Now it is even more confusing because the package is `ldshrink` but the function is `LDshrink`. I see 106 instances mentioning "LDshrink" (case sensitive):

```bash
$ cd ldshrink
$ grep -r LDshrink * | wc -l
106
```

**Comment by xiangzhu** [comment]
@pcarbo  This will definitely be taken care of. Rest assured.
