### ISSUE TITLE
One question on the "theta shrinkage"

### ISSUE THREAD

**Issue by privefl** [stephenslab/LDshrink#33]
I'm referring to 
https://github.com/stephenslab/rss/blob/6e9c8f08e82996ee1364f65dec491d84b6bcac26/misc/get_corr.m#L76-L77
and
https://github.com/stephenslab/rss/blob/6e9c8f08e82996ee1364f65dec491d84b6bcac26/misc/get_corr.m#L139

theta seems to be very small for all sample sizes, even small ones like 100; I'm therefore wondering if this has any effect at all?

Thanks,
Florian

**Comment by xiangzhu** [comment]
@privefl  Thanks for the suggestion.

I have transferred the original issue on `theta` parameter to our `ldshrink` repo, which focus on LD estimates.

Please feel free to add your thoughts/comments here.

**Comment by privefl** [comment]
I have tried some shrinkage in the form of `(1-s) R + s I`, and it often needs `s > 0.1` to make a difference.
Therefore my question on theta being very small.

The problem with this approach is that `s` is an extra parameter; it would be nice to get a default value for it. 
But in fact, it seems to be quite dependent on the mismatching between LD and sumstats.

**Comment by xiangzhu** [comment]
@privefl  Thanks for the information.

In your formulation `(1-s) R + s I`, `s` is a free parameter and it seems we better estimate it from data. However, this is different from the `theta` in Wen-Stephens estimator, which is related to mutation and determined by sample size.

Your formulation seems to be a lot closer to this work than ours: https://doi.org/10.1093/bioinformatics/btu416. Perhaps you can look at their software regarding a good default value on `s`. (Related issue: #12)

Your formulation `(1-s) R + s I` also reminds me of the Ledoit-Wolf estimator (JMA, 2004) in covariance matrix estimation literature: https://doi.org/10.1016/S0047-259X(03)00096-4. Perhaps this 2004 JMA paper can provide additional theoretical insights?

**Comment by privefl** [comment]
Thanks, I'll look at these.

**Comment by stephens999** [comment]
we have also used this model, and my student @Yuxin Zou
***@***.***> has
a
(unpublished) way to estimate s in this model. Perhaps you can follow up
with us by email if you are interested in the details.
Matthew

**Comment by xiangzhu** [comment]
@privefl @stephens999 @zouyuxin 

FYI the Ledoit-Wolf estimator (JMA, 2004) that I mentioned on April 11 has been formally used in the following eQTL study.

Paper: https://doi.org/10.1016/j.ajhg.2015.11.021

Relevant paragraph:
![Screenshot from 2021-05-31 15-56-59](https://user-images.githubusercontent.com/5986023/120235827-e3b98a00-c228-11eb-9622-a57272882bc3.png)

**Comment by privefl** [comment]
It does not seem particularly different when interested in the correlation matrix as the trace is then N.
So the question is more, is there any good value for beta?
