### ISSUE TITLE
Segmentation Fault when merging ldm files with GCTB

### ISSUE THREAD

**Issue by alexisregelson** [stephenslab/LDshrink#35]
Hello,
I just started using the GCTB software but am running into an issue when I try to merge sparse ldm files from a single chromsome into one ldm file. I get the following error:
/var/spool/slurmd.cn1605/job55094972/slurm_script: line 13: 82612 Segmentation fault

Here's the basics of the code I ran
gctb --mldm chr1.mldmlist --make-sparse-ldm --out chr1 --thread 16

Thank you,
Alexis

**Comment by xiangzhu** [comment]
@alexisregelson Thanks for your message!

It seems this is an issue related to GCTB, a software package that is not developed or maintained by us.

If so, perhaps you can contact the GCTB developers or maintainers?
