### ISSUE TITLE
Allow people to use a faster `cov()`

### ISSUE THREAD

**Issue by xiangzhu** [stephenslab/LDshrink#5]
https://github.com/stephenslab/LDshrink/blob/a8fdff30a4df3b202a9932aeb9aa4d3debc7d535/R/LDshrink.R#L10

Here the `cov()` seems to be the default one in `R`, but Nick also has a faster `cov()` based on `C` (which does not handle `NA` well though). We should allow people to use this faster one, if they wish and can provide input data **without** `NA`.

**Comment by CreRecombinase** [comment]
with the latest commit, specifying `na.rm=F` now causes the faster `cov` routine to be used
