### ISSUE TITLE
C++17 requirement is limiting

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/LDshrink#7]
@CreRecombinase @xiangzhu Can you find a way to use replace the C++17 requirement (in the `Makevars` file) with the C++11 requirement, for example? The C++17 standard is much less widely supported; compare [this](https://gcc.gnu.org/projects/cxx-status.html#cxx11) and [this](https://gcc.gnu.org/projects/cxx-status.html#cxx17). In the interest of making the LDshrink package as accessible as possible, can you try to find a way to avoid using C++17 features?

Thanks to @jean997 for identifying this issue.

**Comment by CreRecombinase** [comment]
I've removed the c++17 requirement with the latest commit
